# Generated by Django 4.0.1 on 2023-09-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('image', models.CharField(max_length=50)),
                ('preview_link', models.TextField()),
            ],
        ),
    ]
